version: '1.0'

services:
  

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Openframe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
      
      
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Openframe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - db_data:/var/lib/postgresql/data
                                                                                                                      

volumes:
  db_data:
